# Generated by Django 4.2.4 on 2023-08-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('category', models.TextField(choices=[('men', 'Men'), ('women', 'Women'), ('accessory', 'Accessory')])),
                ('price', models.FloatField()),
                ('stars', models.FloatField()),
                ('bonus', models.FloatField()),
                ('featured', models.BooleanField(default=False)),
                ('best_seller', models.BooleanField(default=False)),
                ('desc', models.TextField()),
                ('colors', models.JSONField()),
                ('images', models.JSONField()),
                ('sizes', models.TextField(choices=[('normal', 'Normal'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')])),
            ],
        ),
    ]
