# Generated by Django 4.2.4 on 2023-09-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_colors_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('men', 'Men'), ('women', 'Women'), ('accessories', 'Accessories')]),
        ),
    ]
