# Generated by Django 4.2.4 on 2023-08-22 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('product_id', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
