# Generated by Django 4.2.4 on 2023-08-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='category',
            field=models.TextField(choices=[('men', 'Men'), ('women', 'Women'), ('accessory', 'Accessory')]),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.TextField(choices=[('normal', 'Normal'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')]),
        ),
    ]
